    graph LR
        A(R1 & R2) --> B{Dry run}
        B -->|Yes| C[Reader (input)]
        C --> J{ID match}
        J --> K[PAIRS ARE DESYNCHRONIZED]
        J -->|Yes| D{Hash unique}
        D -->|No| C
        D -->|Yes| E[Writer]
        D -->|Yes| F[Add to table]
        F --> C

        B --> |No| G{output exist}
        G --> |No| C
        G -->|Yes| H{Compressed}
        H --> |Yes| C
        H --> |No| I[Reader (output)]
        I --> F

%% OXDRAW LAYOUT START
%% {
%%   "nodes": {
%%     "D": {
%%       "x": 1256.8434,
%%       "y": 225.0
%%     },
%%     "E": {
%%       "x": 1470.0,
%%       "y": 225.0
%%     },
%%     "F": {
%%       "x": 1111.7434,
%%       "y": 100.00489
%%     },
%%     "I": {
%%       "x": 883.1,
%%       "y": 100.00489
%%     },
%%     "J": {
%%       "x": 997.4217,
%%       "y": 225.0
%%     },
%%     "H": {
%%       "x": 609.8266,
%%       "y": 100.00489
%%     },
%%     "G": {
%%       "x": 350.0,
%%       "y": 100.0
%%     },
%%     "C": {
%%       "x": 610.17346,
%%       "y": 225.0
%%     },
%%     "K": {
%%       "x": 997.4217,
%%       "y": 20.0
%%     }
%%   },
%%   "edges": {
%%     "F --> C": {
%%       "points": [
%%         {
%%           "x": 1111.7434,
%%           "y": 150.0
%%         },
%%         {
%%           "x": 780.0,
%%           "y": 150.0
%%         }
%%       ]
%%     },
%%     "D --> F": {
%%       "points": [
%%         {
%%           "x": 1256.8434,
%%           "y": 150.0
%%         },
%%         {
%%           "x": 1256.8434,
%%           "y": 100.0
%%         }
%%       ]
%%     },
%%     "C --> J": {
%%       "points": [
%%         {
%%           "x": 930.0,
%%           "y": 225.0
%%         }
%%       ]
%%     },
%%     "D --> C": {
%%       "points": [
%%         {
%%           "x": 1256.8434,
%%           "y": 290.0
%%         },
%%         {
%%           "x": 997.4217,
%%           "y": 290.0
%%         },
%%         {
%%           "x": 609.8266,
%%           "y": 290.0
%%         }
%%       ]
%%     }
%%   }
%% }
%% OXDRAW LAYOUT END
