graph LR
    A(R1) --> B{Dry run}
    B -->|Yes| C[Reader (input)]
    C --> D{Hash unique}
    D -->|No| C
    D -->|Yes| E[Writer]
    D -->|Yes| F[Add to table]
    F --> C

    B --> |No| G{output exist}
    G --> |No| C
    G -->|Yes| H{Compressed}
    H --> |Yes| C
    H --> |No| I[Reader (output)]
    I --> F

%% OXDRAW LAYOUT START
%% {
%%   "nodes": {
%%     "A": {
%%       "x": 150.0,
%%       "y": 227.6248
%%     },
%%     "E": {
%%       "x": 1430.0,
%%       "y": 227.6248
%%     },
%%     "F": {
%%       "x": 1080.0,
%%       "y": 104.50841
%%     },
%%     "C": {
%%       "x": 574.6273,
%%       "y": 230.2496
%%     },
%%     "G": {
%%       "x": 350.0,
%%       "y": 104.50822
%%     },
%%     "H": {
%%       "x": 574.6331,
%%       "y": 104.50822
%%     },
%%     "I": {
%%       "x": 840.0,
%%       "y": 104.50841
%%     }
%%   },
%%   "edges": {
%%     "D --> F": {
%%       "points": [
%%         {
%%           "x": 1214.1,
%%           "y": 160.34993
%%         },
%%         {
%%           "x": 1214.1,
%%           "y": 180.0
%%         },
%%         {
%%           "x": 1214.1,
%%           "y": 104.50841
%%         }
%%       ]
%%     },
%%     "D --> C": {
%%       "points": [
%%         {
%%           "x": 910.0,
%%           "y": 225.0
%%         }
%%       ]
%%     },
%%     "C --> D": {
%%       "points": [
%%         {
%%           "x": 574.6273,
%%           "y": 280.0
%%         },
%%         {
%%           "x": 900.0,
%%           "y": 280.0
%%         },
%%         {
%%           "x": 1214.1,
%%           "y": 280.0
%%         }
%%       ]
%%     },
%%     "F --> C": {
%%       "points": [
%%         {
%%           "x": 1080.0,
%%           "y": 160.34993
%%         },
%%         {
%%           "x": 742.7005,
%%           "y": 160.34993
%%         },
%%         {
%%           "x": 742.7005,
%%           "y": 227.6248
%%         }
%%       ]
%%     }
%%   }
%% }
%% OXDRAW LAYOUT END
